apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-web-app
  annotations:
    kubernetes.io/change-cause: apache
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: apache-php
          image: kaziri/apache-php

          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 20Mi
              cpu: 20m
##          volumeMounts:
##            - name: apache-config
##              mountPath: /var/www/html
##              readOnly: false
##          securityContext:
##            readOnlyRootFilesystem: false
##      volumes:
##        - name: apache-config
##          configMap: 
##            name: apache-config-map
##            defaultMode: 0666
