apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-web-app
              port:
                number: 80
