apiVersion: v1
kind: Service
metadata:
  name: deploy-web-app
  namespace: webapp
  resourceVersion: "370782"
  uid: 656eb2aa-4a35-4acf-9786-5439b9a71f85
spec:
  clusterIP: 10.109.168.165
  clusterIPs:
  - 10.109.168.165
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31040
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: web-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

